"""add a link between the habit and the reminder

Revision ID: 2129876d7a8e
Revises: 97dc8a031509
Create Date: 2025-05-12 19:04:19.623159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2129876d7a8e'
down_revision: Union[str, None] = '97dc8a031509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('habit_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reminders_habit_id'), 'reminders', ['habit_id'], unique=False)
    op.create_foreign_key(None, 'reminders', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_habit_id'), table_name='reminders')
    op.drop_column('reminders', 'habit_id')
    # ### end Alembic commands ###
