"""create table users_tokens

Revision ID: 631ca1e00ad0
Revises: a593f184beb2
Create Date: 2025-05-08 22:44:04.519589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631ca1e00ad0'
down_revision: Union[str, None] = 'a593f184beb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tokens_token'), 'users_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_users_tokens_user_id'), 'users_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tokens_user_id'), table_name='users_tokens')
    op.drop_index(op.f('ix_users_tokens_token'), table_name='users_tokens')
    op.drop_table('users_tokens')
    # ### end Alembic commands ###
