"""drop table Chat

Revision ID: a593f184beb2
Revises: 31061a3e2694
Create Date: 2025-05-08 22:37:10.798790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a593f184beb2'
down_revision: Union[str, None] = '31061a3e2694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_chat_id', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    op.create_index('ix_chats_chat_id', 'chats', ['chat_id'], unique=True)
    # ### end Alembic commands ###
