"""Add column week_days in Habbit

Revision ID: e3087efc5bea
Revises: 9d14513ea327
Create Date: 2025-05-23 17:34:02.903487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3087efc5bea'
down_revision: Union[str, None] = '9d14513ea327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('week_days', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'week_days')
    # ### end Alembic commands ###
