"""Добавила таблицу для трекера привычек

Revision ID: eaad875c283e
Revises: 9aca5605a12a
Create Date: 2025-05-11 13:51:00.035268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaad875c283e'
down_revision: Union[str, None] = '9aca5605a12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date_mark', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date_mark', name='uq_habit_date')
    )
    op.create_index(op.f('ix_habit_trackers_date_mark'), 'habit_trackers', ['date_mark'], unique=False)
    op.create_index(op.f('ix_habit_trackers_habit_id'), 'habit_trackers', ['habit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_trackers_habit_id'), table_name='habit_trackers')
    op.drop_index(op.f('ix_habit_trackers_date_mark'), table_name='habit_trackers')
    op.drop_table('habit_trackers')
    # ### end Alembic commands ###
